### ISSUE TITLE
Common input boxes are not clickable on the placeholder

### ISSUE THREAD

**Issue by prasanthchaduvula** [saeloun/miru-web#1100]
### Description
- We can't click on the placeholder text of the input box to type.

https://share.vidyard.com/watch/5NS2GrBA8S56NpC8Y7NPRd

<img width="552" alt="Screenshot 2023-03-02 at 6 21 49 PM" src="https://user-images.githubusercontent.com/52771571/222434082-44e37931-3bb1-4727-8d3c-3936a7a84b29.png">

**Comment by onkar-saeloun** [comment]
@prasanthchaduvula can you please tell me how can I navigate this path?
I tried with the latest develop branch but didn't work. Isthe issue in your ongoing PR?

**Comment by prasanthchaduvula** [comment]
@onkar-saeloun you can verify the signin component and signup component on develop branch
or you can test them https://github.com/saeloun/miru-web/pull/1106

**Comment by prasanthchaduvula** [comment]
Let me fix it
