### ISSUE TITLE
Add a CONTRIBUTING.md file with contribution guidelines to repository.

### ISSUE THREAD

**Issue by sonamvg** [saeloun/miru-web#1417]
Add a CONTRIBUTING.md file with contribution guidelines to Miru repository for Hacktoberfest.

**Comment by akhilgkrishnan** [comment]
@sonamvg We already have a [CONTRIBUTING.md](https://github.com/saeloun/miru-web/blob/develop/CONTRIBUTING.md) page for Miru.

**Comment by sonamvg** [comment]
@gowsik-ragunath Please check if we need any edits to the file. The issue can be closed post that.

**Comment by gowsik-ragunath** [comment]
@sonamvg We have all the information in the [contribution.md ](https://github.com/saeloun/miru-web/blob/develop/CONTRIBUTING.md) page.

But in contribution page, it is mentioned that issues are listed in [issues](https://github.com/saeloun/miru-web/issues) page but we are using Notion to track the existing issues, should we add Notion link there?

**Comment by gowsik-ragunath** [comment]
Closing this issue as the contribution page has all the correct content.

Confirm with @supriya3105 that the issues will be added on Github issues page for Hacktoberfest.

**Comment by akhilgkrishnan** [comment]
For the Hacktoberfest, the tickets should be added in the Github issues for tracking. For us we can continue to use Notion.
