### ISSUE TITLE
Move the installation/setup guidelines to Miru Docs

### ISSUE THREAD

**Issue by akhilgkrishnan** [saeloun/miru-web#1457]
### Describe the solution you'd like

- Remove the installation and testing guideline from `Readme` and move the updated content to [Miru Docs](https://github.com/saeloun/miru-docs)

**Comment by supriya3105** [comment]
@apoorv1316 Please work on moving the guidelines to Miru docs and ensure that the guidelines are upto date.

**Comment by supriya3105** [comment]
Assigned to @prasanthchaduvula in Apoorv's absence

**Comment by charann29** [comment]
If there isn't anyone currently assigned to this task, I'd like to take it on. Kindly assign this issue to me, @prasanthchaduvula

**Comment by charann29** [comment]
If no one currently working on this task, I'd like to take it on. Kindly assign this issue to me, @supriya3105

**Comment by prasanthchaduvula** [comment]
@charann29 currently we are working on this. This is an internal task for Miru docs

**Comment by supriya3105** [comment]
@charann29 There are other open issues that you can work. Please go through the issues tagged as hacktoberfest.
