### ISSUE TITLE
The first letter of the employee type field should be capitalised in the read mode on organisation settings page

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1481]
### Description

The first letter of the employee type field is not capitalised in the read mode on organization settings page

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

The first letter of the employee type field should be capitalised in the read mode on organization settings page

### What is the current behaviour?

The first letter of the employee type field is not capitliazed in the read mode on organization settings page

### How to reproduce the issue?

1. Login as any user 
2. Click on settings from the left navigation menu
3. Click on organization settings 
4. Click on edit button 

### Screenshots or Screencast

Edit mode - <img width="1409" alt="Screenshot 2023-09-25 at 1 07 02 PM" src="https://github.com/saeloun/miru-web/assets/91338424/cc4d0341-e19b-4bdd-91a7-d7c8a8d89102">

Read mode - 
<img width="1404" alt="Screenshot 2023-09-25 at 1 04 41 PM" src="https://github.com/saeloun/miru-web/assets/91338424/1c3d77c2-3df9-4537-9dc7-069f2ad9af93">

### Please provide any traces or logs that could help here.

NA

### Any possible solutions?

NA

**Comment by ameen4455** [comment]
Hi! Can I work on this?

**Comment by supriya3105** [comment]
@ameen4455 Sure. Please go ahead. 

Once you have raised the pull request, please add hacktoberfest label to it and assign it to Shruti for review. Once the PR is approved, I will be merging the PR's

**Comment by supriya3105** [comment]
@ameen4455 Are you working on this ?

**Comment by ameen4455** [comment]
@supriya3105 yes I am
