### ISSUE TITLE
Populate the designation under the profile photo, if the designation field is populated on the employment details tab

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1484]
### Is your proposal related to a problem?

As a user, I should be able to view the users designation under my profile photo instead of having to navigate to the employment details tab.

### Describe the solution you'd like

Populate the designation under the profile photo, if the designation field is populated on the employment details tab

Steps: 
1. Login as any user in Miru 
2. Click on settings on the left navigation bar
3. Go to employment details tab 
4. if the designation field is populated, the value should be populated under the profile photo 

Desktop 
![image](https://github.com/saeloun/miru-web/assets/91338424/8c22117c-5b49-428d-824a-07b08cf5c7ec)

Mobile responsive page 

![image](https://github.com/saeloun/miru-web/assets/91338424/7afea3c0-2c82-4c6f-b6e7-29d8c31ff4a3)

**Comment by jainPrajwal** [comment]
Hey @supriya3105  would like to contribute! Can you assign this task to me? Thanks!

**Comment by supriya3105** [comment]
@jainPrajwal Assigned the issue to you. Once you raise a PR , please assign the PR for review to @prasanthchaduvula . Once it's approved by him , I will merge it.

**Comment by jainPrajwal** [comment]
Hi @supriya3105, I am trying to do the setup on Windows, but facing issues.
Is there any other helpful doc for the setup?
OS: Windows 10 Pro
Version: 1803

Are all the steps mentioned in the Installation README mandatory to run the app?
Few issues that I faced were:

1. even after installing rvm, `rvm list rubies` threw an error. 
2. brew does not work on windows. You need a Windows Subsystem for Linux.
3. installing elastic search threw error.

Thank you.

**Comment by supriya3105** [comment]
Tagging @prasanthchaduvula to respond to the question.

**Comment by prasanthchaduvula** [comment]
@jainPrajwal follow the below steps
- Yes, All the packages mentioned in the README are required. you need ruby, postgresql, elasticsearch, and redis.
- After having all of these, you can run `./bin/setup` to set up the app or follow the steps mentioned in the same file. 
- Share the error you are getting on elasticsearch installation or check this https://www.elastic.co/guide/en/elasticsearch/reference/7.17/zip-windows.html to install elasticsearch on Windows.
- Check your ruby version if ruby is installed using `ruby -v `
- Regarding rvm, please follow this doc https://rvm.io/rubies/list

**Comment by reettikgoswami** [comment]
@jainPrajwal  Have you ever given Docker a try for setting up the project?
[LInk](https://github.com/saeloun/miru-web/blob/develop/docs/docs/contributing-guide/setup/docker.md) doc might help.

**Comment by apoorv1316** [comment]
@jainPrajwal Were you able to setup the app?

**Comment by jainPrajwal** [comment]
Thank you @prasanthchaduvula for your reply.
Will try these out over the weekend.

**Comment by jainPrajwal** [comment]
@reettikgoswami  No, I haven't  used dockers.
Will definitely go through the docs. Thanks a lot.

**Comment by jainPrajwal** [comment]
> @jainPrajwal Were you able to setup the app?

@apoorv1316 No, I still need to go through the steps mentioned in the comments.

**Comment by apoorv1316** [comment]
@jainPrajwal Have you started working on this?

**Comment by sainikhil1605** [comment]
Hey @supriya3105 I would like to contribute. Can you assign this task to me? Thanks!
