### ISSUE TITLE
the date format in the downloaded invoice pdf is in the fixed format of DD-MM-YYYY whereas it should be as per defined under organization settings

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1485]
### Description

the date format in the downloaded invoice pdf is in the fixed format of dd-mm-yyyy whereas it should be as per defined under organization settings

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

The date format should be as what is selected on the organization settings page by the admin/owner user role. 

### What is the current behaviour?

By default the date format on the downloaded invoice pdf is dd-mm-yyyy

### How to reproduce the issue?

1. login as admin or owner user role
2. click on settings 
3. go to organization settings and click on edit 
4. select the date format as MM-DD-YYYY
5. click on Save
6. go to invoice tab 
7. generate new invoice and send it 
8. After sending the invoice, go the more menu option and click on download option
9. open the invoice from downloads folder. 

### Screenshots or Screencast

Organization setting
<img width="1440" alt="Screenshot 2023-09-26 at 12 56 31 PM" src="https://github.com/saeloun/miru-web/assets/91338424/17799dfe-c71d-4d2d-b507-897ebd89e68e">

Invoice PDF 

<img width="709" alt="Screenshot 2023-09-26 at 1 00 51 PM" src="https://github.com/saeloun/miru-web/assets/91338424/5680d24b-c602-4179-aedd-ef51bac47151">

**Comment by nayangoyal** [comment]
Hi, @supriya3105 can you assign this issue to me? I am new to open source and I want to solve this issue.

**Comment by supriya3105** [comment]
@nayangoyal Assigned the issue to you. Once you raise a PR, please assign for review to @prasanthchaduvula . When the PR is approved by him, I will merge them.

**Comment by apoorv1316** [comment]
@nayangoyal Were you able to start working on this issue? Feel free to ask for help if you are stuck somewhere

**Comment by nayangoyal** [comment]
I am working on this issue but there is my college academic paper is going on that why I have stopped on working it. On 5th October my paper was ended. So, I will be able to start working on this issue again, if you don't mind I will start working on this issue from 5th October.

**Comment by nayangoyal** [comment]
@apoorv1316

**Comment by apoorv1316** [comment]
@nayangoyal Okay, no worries. LMK, if you need any help

**Comment by apoorv1316** [comment]
@nayangoyal Did you start working on this?

**Comment by trishanu-init** [comment]
@apoorv1316 @supriya3105 Please assign this issue to me , i would push the code ASAP

**Comment by apoorv1316** [comment]
@trishanu-init Assigned it to you
