### ISSUE TITLE
Chrome extension for miru

### ISSUE THREAD

**Issue by shubhamku044** [saeloun/miru-web#1490]
### Is your proposal related to a problem?

While working we always need to open the website and start time-tracking and to close it, we need to open the website.

### Describe the solution you'd like
We should have a chrome extension from where we can a do few things like time-tracking, creating new projects etc.

**Comment by apoorv1316** [comment]
Hi Shubham, We are already working on a desktop app for miru and the Chrome extension is not in our plan for now. Thanks for the suggestion though I will discuss it with the team. Closing this issue for now. cc @supriya3105
