### ISSUE TITLE
Develop the allocated devices tab under the settings option for read mode

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1492]
### Is your proposal related to a problem?

Currently, the admin tracks the devices allocated to a team members through an excel sheet. 

### Describe the solution you'd like

I would like the devices tracking to be handled online through the Miru application, where the admin can add the details 

As part of the tasks involving the feature are. 

- [ ] Add the Allocated Devices tab under the Employment details tab for employee role 
- [ ] Add the Allocated Devices tab under the Employment details tab under the personal settings menu for admin/owner role
- [ ] Develop the page in read mode as per the UI designs. 
- [ ] Please use the common components such as for the header that has the Allocated devices during the development. 

Employee Role Designs 

![image](https://github.com/saeloun/miru-web/assets/91338424/6a56315a-4f17-4fee-b4af-bb24fcc77678)

Admin/Owner Role designs 

![image](https://github.com/saeloun/miru-web/assets/91338424/50a30fb8-dbf2-4f4b-bd3a-1e1c06746e58)

### Describe the user flow

1. Login as employee user 
2. Click on settings 
3. The user should be able to view the Allocated devices tab below the employment details tab
4. On clicking the tab, user should be able to view the page in read mode. 

1. Login as admin/owner user 
2. Click on settings 
3. The user should be able to view the Allocated devices tab below the employment details tab under the personal setting expandable menu 
4. On clicking the tab, user should be able to view the page in read mode.

**Comment by reettikgoswami** [comment]
@supriya3105 Can I work on this issue?

**Comment by supriya3105** [comment]
@reettikgoswami Assigned the issue to you.

**Comment by reettikgoswami** [comment]
@supriya3105, Could you help me who should be assigned to review the pull request?

**Comment by supriya3105** [comment]
@reettikgoswami The related PR is assigned to Prasanth for review.
