### ISSUE TITLE
Add Google Tag to all the pages of the Miru Application

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1493]
### Is your proposal related to a problem?

In order to capture events and analyse them , we need to be able to do so using google tag manager. Hence we need to add the google tag to each page of the Miru application 

For e.g. we need want to track how many times the Add new client button was clicked the client page then that can be done so using google tag manager.

### Describe the solution you'd like

Below is the Google tag for Miru account. Copy and paste it in the code of every page of your website, immediately after the <head> element. Don’t add more than one Google tag to each page.

<script async src="https://www.googletagmanager.com/gtag/js?id=G-KXG1PCPVHT"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());

gtag('config', 'G-KXG1PCPVHT');
</script>

**Comment by ameen4455** [comment]
Could I take this up?

**Comment by micahyoung324** [comment]
I can give this a shot as well.

**Comment by supriya3105** [comment]
@micahyoung324 Assigning this to you.

**Comment by micahyoung324** [comment]
I am sorry but you can assign ammen4455 instead.
