### ISSUE TITLE
Use common loader across all the pages of the application 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1494]
### Is your proposal related to a problem?

Currently, the loader is added on the invoice list page and pages under settings common/loader. The same loader needs to be used across the remaining pages. 

### Describe the solution you'd like

Use the loader across all the pages of the application 

```
import Loader from "common/Loader"

<div className="flex h-80v w-full flex-col justify-center">
      <Loader />
</div>
```

**Comment by rayyyyofsunshine** [comment]
Hey, can you assign this to me? I'd be willing to work on this.

**Comment by supriya3105** [comment]
@rayyyyofsunshine Assigned the issue to you. When you raise the PR, please assign it for review to @prasanthchaduvula .

**Comment by apoorv1316** [comment]
@rayy40 Were you able to start working on this issue? Feel free to ask for help if you are stuck somewhere.

**Comment by apoorv1316** [comment]
@rayy40 I've replied to your query on discord.

**Comment by rayy40** [comment]
Hey @apoorv1316, I am trying to set it up using wsl2 by going through the docs of ubuntu, if I am unable to do so I'll update accordingly and unassign myself so that someone else can do it.

**Comment by rayy40** [comment]
> Hey @apoorv1316, I am trying to set it up using wsl2 by going through the docs of ubuntu, if I am unable to do so I'll update accordingly and unassign myself so that someone else can do it.

Have set up the application successfully, will be raising the PR today.

**Comment by apoorv1316** [comment]
@rayy40 Awesome. You were able to set up using WSL? If yes, would you be interested in writing the documentation for Windows using WSL

**Comment by rayy40** [comment]
> @rayy40 Awesome. You were able to set up using WSL? If yes, would you be interested in writing the documentation for Windows using WSL

Yeah I was able to set it up using WSL. I'd be happy to tell you how I did it.

Can you help me with locating the pages? The Loader needs to be in all the pages, so the files named with `index.tsx` are all pages right? Or is there a specific convention the project is following?

**Comment by apoorv1316** [comment]
> > @rayy40 Awesome. You were able to set up using WSL? If yes, would you be interested in writing the documentation for Windows using WSL
> 
> Yeah I was able to set it up using WSL. I'd be happy to tell you how I did it.
> 
> Can you help me with locating the pages? The Loader needs to be in all the pages, I am able to get the routes, but how can I get the sub routes too? Or is there a better way to do this?

@Shruti-Apte Can you respond to the above query? 
@rayy40 Yes please document the steps, you can see how we have documented for Mac, Ubuntu, and Docker. Try to follow a similar approach. Thanks!
https://docs.miru.so/category/environment-setup

cc @akhilgkrishnan @prasanthchaduvula

**Comment by rayy40** [comment]
@apoorv1316 I will be documenting the steps by the end of the day.

And an update on the fix, I went through all the routes in the _src/constants/routes_ file and updated the Loader for all of them.
Had some doubts related to some files, which were missing the `isLoading` state.

**Comment by akhilgkrishnan** [comment]
> > > @rayy40 Awesome. You were able to set up using WSL? If yes, would you be interested in writing the documentation for Windows using WSL
> > 
> > 
> > Yeah I was able to set it up using WSL. I'd be happy to tell you how I did it.
> > Can you help me with locating the pages? The Loader needs to be in all the pages, I am able to get the routes, but how can I get the sub routes too? Or is there a better way to do this?
> 
> @Shruti-Apte Can you respond to the above query? @rayy40 Yes please document the steps, you can see how we have documented for Mac, Ubuntu, and Docker. Try to follow a similar approach. Thanks! https://docs.miru.so/category/environment-setup
> 
> cc @akhilgkrishnan @prasanthchaduvula

This is a great thing. @rayy40 You can work on the documentation in a seperate PR.

@apoorv1316 Can you create a separate issue for "Windows Setup"

**Comment by prasanthchaduvula** [comment]
> @apoorv1316 I will be documenting the steps by the end of the day.
> 
> And an update on the fix, I went through all the routes in the _src/constants/routes_ file and updated the Loader for all of them. Had some doubts related to some files, which were missing the `isLoading` state.

Please go through the codebase, wherever <Loader /> component is used, and try to verify the classnames of it to make sure whether it styles properly or not and is centre aligned.

**Comment by prasanthchaduvula** [comment]
@rayy40 Regarding missing the `isLoading` state check is there any other state they are using to render the `Loader`

**Comment by rayy40** [comment]
> @rayy40 Regarding missing the `isLoading` state check is there any other state they are using to render the `Loader`

They are not using the `Loader` at all.
So I was wondering whether I should add Loader to them too? (These files don't have the `isLoading` state) 
But it seems like they can use a `Loader` since they are fetching data.
Please let me know about this.

**Comment by rayy40** [comment]
> Please go through the codebase, wherever component is used, and try to verify the classnames of it to make sure whether it styles properly or not and is centre aligned.

I have styled the Loader properly with the components used in routes.
I just had a confusion on whether to apply the Loader to those components too which doesn't have a `isLoading` state, and by that I mean they don't have any state to check for loading. So, should I make one? Or should I just let them be?

**Comment by prasanthchaduvula** [comment]
@rayy40 We need a `Loader` on all the react route pages.

**Comment by rayy40** [comment]
Hey @prasanthchaduvula , I have raised the PR including the desired changes. Can you please review it?

**Comment by apoorv1316** [comment]
@rayy40 Thanks for working on the issue. There are more unassigned issues. Feel free to pick one of them.
