### ISSUE TITLE
auto saving of timesheet entry to local storage until it is saved

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1495]
### Is your proposal related to a problem?

auto saving of timesheet entry to local storage until it is saved. 

### Describe the solution you'd like

1. Login as any user 
2. On the time tracking tab, click on new entry 
3. Fill the required fields and refresh the screen 
4. After page refresh the previously filled details should be loaded on the page 

### Requirement explanation video
https://www.loom.com/share/bb2907fec1264066ba38299aa46c9a39

**Comment by Labhk** [comment]
can u assign me this issue??

**Comment by apoorv1316** [comment]
@Labhk Were you able to start working on this issue? Feel free to ask for help if you are stuck somewhere.

**Comment by Labhk** [comment]
> @Labhk Were you able to start working on this issue? Feel free to ask for help if you are stuck somewhere.

can u review my PR

**Comment by Labhk** [comment]
I won't be able to work on this issue for now u can assign some else plz.

**Comment by qianzhong516** [comment]
Hey, I'm happy to work on this issue. Could you please assign it to me?

**Comment by apoorv1316** [comment]
> Hey, I'm happy to work on this issue. Could you please assign it to me?

@qianzhong516 Sure assigning it to you. Please watch the loom video to understand the requirements. Let me know if you have any doubts or need help.
https://www.loom.com/share/bb2907fec1264066ba38299aa46c9a39

**Comment by qianzhong516** [comment]
@apoorv1316 I have some concerns on showing the unsaved info in a form had been edited. I can see that when you click edit on an entry, the server data is displayed and the update button is available for clicking. The UI looks exactly the same for a form shows the unsaved info, so user won't be able to tell whether if they are looking at the unsaved info, or the saved info. I suggest to add a tip to remind user that they have some unsaved info in the form as the next step.

**Comment by apoorv1316** [comment]
> @apoorv1316 I have some concerns on showing the unsaved info in a form had been edited. I can see that when you click edit on an entry, the server data is displayed and the update button is available for clicking. The UI looks exactly the same for a form shows the unsaved info, so user won't be able to tell whether if they are looking at the unsaved info, or the saved info. I suggest to add a tip to remind user that they have some unsaved info in the form as the next step.

@qianzhong516 It's a valid point. 
@supriya3105 Can you please think about what can be done in the above case?

**Comment by supriya3105** [comment]
@qianzhong516 Thank you for the suggestion. I have added it to the backlog, discuss with the team and plan its implementation . For now, let's focus on getting the entry saved on local storage.

**Comment by qianzhong516** [comment]
Hey, please review my PR 👆, thanks
