### ISSUE TITLE
Feature Button has a bug

### ISSUE THREAD

**Issue by Shivansh175** [saeloun/miru-web#1497]
### Description

Feature button shows up the features upon being hovered but features menu must fade when cursor is out of the button, it still remains opened.

### What is the expected behaviour?
Features list must hide when mouse is no more over the features button.

### What is the current behaviour?

https://github.com/saeloun/miru-web/assets/112273961/b877f688-8282-44e4-b116-9b2748080a8f

### If the bug is confirmed, would you be willing to submit a PR?
Yes please assign it to me

**Comment by akhilgkrishnan** [comment]
Hi @Shivansh175 ,
Thanks for raising this issue. But this website is not part of miru-web respository. However I can raise this issue to our team to fix.

Thanks
