### ISSUE TITLE
The invoice number auto increment is not working correctly. 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1524]
### Description

If the existing invoice number is 039, on generating a new invoice , the invoice number getting automatically populated is 0310. The system is auto incrementing the last number. 

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

The auto increment should work properly. If the last invoice number was 039 then new invoice number should be 040 

### What is the current behaviour?
If the existing invoice number is 039, on generating a new invoice , the invoice number getting automatically populated is 0310. The system is auto incrementing the last number. 

### How to reproduce the issue?

1. Login as admin or owner user
2. Go to invoices module. 
3. Click on new invoice button 
4. Select a client 

The new invoice number should be properly auto incremented and populated on the invoice.

**Comment by Jaideep1702** [comment]
can you assign me this issue.

**Comment by supriya3105** [comment]
@Jaideep1702 Assigned this you. Please let me know if you have question about the issue.

**Comment by Jaideep1702** [comment]
I had validated it by reproducing the issue.

![image](https://github.com/saeloun/miru-web/assets/91385804/bc23a4b5-2acb-4b37-b07a-ca1961dbb087)

Now, I'm trying to build the project, but I'm facing a few issues. I'm attaching screenshots. Can you help me with them?

![image](https://github.com/saeloun/miru-web/assets/91385804/8f46988e-49da-4bba-91d3-0ec8fc8b076b)

**Comment by supriya3105** [comment]
@apoorv1316 Please help him with the project setup issue.

**Comment by apoorv1316** [comment]
> I had validated it by reproducing the issue.
> 
> ![image](https://user-images.githubusercontent.com/91385804/273404180-bc23a4b5-2acb-4b37-b07a-ca1961dbb087.png)
> 
> Now, I'm trying to build the project, but I'm facing a few issues. I'm attaching screenshots. Can you help me with them?
> 
> ![image](https://user-images.githubusercontent.com/91385804/273405425-8f46988e-49da-4bba-91d3-0ec8fc8b076b.png)

@Jaideep1702 Can you try be removing the`RUN RAILS_ENV=$RAILS_ENV rails assets:precompile` line from Dockerfile.local

**Comment by apoorv1316** [comment]
@Jaideep1702 Were you able to setup and run the app?

**Comment by Jaideep1702** [comment]
@apoorv1316 facing this issue 

![Screenshot 2023-10-11 131142](https://github.com/saeloun/miru-web/assets/91385804/8c57ce89-1e06-4f6c-b3a7-fb60f20050f7)

![Screenshot 2023-10-11 131111](https://github.com/saeloun/miru-web/assets/91385804/74370f12-bfed-453e-b9b4-eb5ca68d872a)

![image](https://github.com/saeloun/miru-web/assets/91385804/b02c3c7c-e130-465a-ac16-c0b435afad0b)

**Comment by apoorv1316** [comment]
Hi @Jaideep1702 Please join the discord server and let's chat there. I will help you to fix the errors
https://discord.gg/U9nyKCuy
