### ISSUE TITLE
Documentation: Setup for windows app

### ISSUE THREAD

**Issue by apoorv1316** [saeloun/miru-web#1529]
Write documentation for setting up the app for the Windows environment using WSL2

**Comment by apoorv1316** [comment]
@rayy40 Assigning this issue to you.

**Comment by rayy40** [comment]
Hey @apoorv1316 , I'll be happy to work on this.

**Comment by rayy40** [comment]
Hey @apoorv1316 , I have raised a PR including the documentation to setup app locally using Windows.
Can you please review it, and tell me if any changes are required?
