### ISSUE TITLE
Develop the edit page of allocated devices tab 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1533]
Is your proposal related to a problem?

Currently, the admin tracks the devices allocated to a team members through an excel sheet.

Describe the solution you'd like

I would like the devices tracking to be handled online through the Miru application, where the admin can add the details

As part of the tasks involving the feature are.

- [ ]  Develop the page in edit mode as per the UI designs.
- [ ] On clicking cancel button the , user should view the page in read mode. 
- [ ] On clicking edit button the user should be able to view the page in edit mode. 

Designs

![image](https://github.com/saeloun/miru-web/assets/91338424/be027ec0-1869-4381-8b29-9595875673f8)

Describe the user flow

1. Login as employee user
2. Click on settings
3. The user should be able to view the Allocated devices tab below the employment details tab
4. On clicking the tab, user should be able to view the page in read mode.
5. On clicking edit button the user should be able to view the page in edit mode. 
6. On clicking cancel, the changes made by the user should be discarded and user should be view the page in edit mode. 
7. On clicking update, the changes made by their user should be saved and user should be able to view the page in read mode with the updated values. 

Login as admin/owner user

1. Click on settings
2. The user should be able to view the Allocated devices tab below the employment details tab under the personal setting expandable menu
3. On clicking the tab, user should be able to view the page in read mode.
4. 5. On clicking edit button the user should be able to view the page in edit mode. 
6. On clicking cancel, the changes made by the user should be discarded and user should be view the page in edit mode. 
7. On clicking update, the changes made by their user should be saved and user should be able to view the page in read mode with the updated values.

**Comment by reettikgoswami** [comment]
@supriya3105, can you please assign the issue to me.

**Comment by apoorv1316** [comment]
@reettikgoswami Have you started working on this issue?

**Comment by reettikgoswami** [comment]
@apoorv1316, Yes I am working.

**Comment by rayy40** [comment]
Hey @apoorv1316 I'd be happy to work on this, if no one is.

**Comment by apoorv1316** [comment]
@rayy40 Please pick un-assigned issues. Reetik is already working on it

**Comment by supriya3105** [comment]
@reettikgoswami Are you still working on this issue ? Please let me know if you have any questions about the same.

**Comment by reettikgoswami** [comment]
@supriya3105 Yes I am working, Will finish today itself.

**Comment by supriya3105** [comment]
@Shruti-Apte Assigned this issue to you.
