### ISSUE TITLE
Update the year in footer to 2023 for mailer files

### ISSUE THREAD

**Issue by apoorv1316** [saeloun/miru-web#1539]
### Description
In the mailer files the year is set to 2022, we need to update it to **2023**.

List of the files where changes are required
1. `payment.html.erb`
2. `invoice.html.erb`
3.  `client_payment_mailer.html.erb`
4.  `payment.html.erb`
5. `send_payment_reminder.html.erb`
6. `send_reminder.html.erb`

### Screenshot
<img width="1007" alt="Screenshot 2023-10-10 at 11 38 18 AM" src="https://github.com/saeloun/miru-web/assets/18750194/4266aa1d-d07d-4ad8-b1af-ffac7c48c31f">

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

The year should be 2023 in footer

### What is the current behaviour?

The year is 2022

### How to reproduce the issue?

1. Login as admin 
2. Create a new client with an email that you have
3. Create a  billable type project for the above client
4. Add project members and create timesheet entries for the above client & project
5. Send Invoice to the client
6. Send payment reminder from the clients page

### Any possible solutions?

Change the year to 2023 in the files mentioned above

**Comment by swaleha2002** [comment]
Hi there!

I've reviewed the issue regarding updating the year to 2023 in the specified files. I'd be happy to work on this and ensure the year is accurately reflected in the footer.

Could you please assign this issue to me? I'll make the necessary updates promptly.

Thank you!

**Comment by swaleha2002** [comment]
Hi @apoorv1316 

I've reviewed the issue regarding updating the year to 2023 in the specified files. I'd be happy to work on this and ensure the year is accurately reflected in the footer.

Could you please assign this issue to me? I'll make the necessary updates promptly.

Thank you!

**Comment by apoorv1316** [comment]
@swaleha2002 Assigned the issue to you.

**Comment by swaleha2002** [comment]
Thank you @apoorv1316

**Comment by apoorv1316** [comment]
@swaleha2002 Were you able to setup and run the app?

**Comment by swaleha2002** [comment]
I regret to inform you that I am unable to set up and run the app.

**Comment by apoorv1316** [comment]
@swaleha2002 Please join the discord https://discord.gg/T7Bu3Cvx and share what issues are you facing while setting up the app. I will help you to set up the app.

**Comment by swaleha2002** [comment]
okay sure!

**Comment by SaiganeshGurrapu16** [comment]
Hey @apoorv1316  can you assign me if @swaleha2002 is unable to resolve it

**Comment by apoorv1316** [comment]
@SaiganeshGurrapu16 Assigned it to you. Please join Discord and ping there if you need any help
https://discord.gg/dNP3DWUu

**Comment by balaraju-nerati** [comment]
hey @SaiganeshGurrapu16 , are you still working on this issue? If not, i would love work on this issue.

**Comment by apoorv1316** [comment]
@SaiganeshGurrapu16 Have you started working on this?

**Comment by balaraju-nerati** [comment]
hey @apoorv1316 if the assigned person just in case unable to resolve the issue, I would love to try in solving the issue : )

**Comment by vipulnsward** [comment]
We should remove all year references instead like Rails has done- https://github.com/rails/rails/pull/47467/files
