### ISSUE TITLE
Getting Internal server on search on client list page 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1543]
### Description

When the user types the search keyword on the search box on client list page, getting internal server error on toast message 

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

On searching, if there is a matching client then the same should be displayed to the user on the search dropdown. The user should be able to select one of the matching results .  

### What is the current behaviour?

When the user types the search keyword on the search box on client list page, getting internal server error on toast message 

### How to reproduce the issue?

1. Login as an admin or owner user
2. Click on the clients module on left navigation bar
3. enter a keyword in the search box
4.  

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2023-10-11 at 6 39 31 PM" src="https://github.com/saeloun/miru-web/assets/91338424/264b3416-4243-4e79-9f4b-93bca6c5f455">

**Comment by prasanthchaduvula** [comment]
Reindex the client modal fixed it
