### ISSUE TITLE
Show hours logged for employees on clients page

### ISSUE THREAD

**Issue by apoorv1316** [saeloun/miru-web#1544]
### Description
On the `clients` page, we display a list of clients along with the hours logged in the current week. There are two types of user admin and employee. For admin users the hours logged is visible but for employee roles, the hours are not visible on the full-screen laptop, but it is visible for mobile screens. So, we have to make sure that the hours logged must be visible for employee roles on all screen sizes.

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

Hours logged data should be visible for all screen sizes for both admin and employees

### What is the current behaviour?

Hours logged are not visible on full screen for employees

### How to reproduce the issue?

1. Login as employee
2. Create a timesheet entry for a client in the current week
3. Visit clients page

### Screenshots or Screencast
 **Please watch the loom video to understand the issue**

https://www.loom.com/share/3cff2844c8424bb5b7e5693c26c7ab0b

**Comment by rayy40** [comment]
Hey @apoorv1316 , Can I work on this?

**Comment by apoorv1316** [comment]
@rayy40 Assigned it to you.

**Comment by rayy40** [comment]
Hey @apoorv1316 , Can you help me with this a little?
I am unable to figure out in which component is rendering the minutes logged in?

Is it the `Table` component?

If it is, then can you tell me how can I log the data in `tableData`, I am unable to log it in the console. I am not really familiar with ruby on rails. Can you guide me with this?

**Comment by apoorv1316** [comment]
@rayy40 Yes, it is rendered through the table, and the TableData.tsx file col3 is used to display the hours logged. You can use the network tab and response tab from the Chrome console to see the data or you can console the `clientData` on the root index file of the Clients folder.
Also, try to see the CSS classes for the hours logged on the employee role and find that class in the codebase, and try tweaking it and it might fix the issue.
<img width="608" alt="Screenshot 2023-10-16 at 10 03 58 AM" src="https://github.com/saeloun/miru-web/assets/18750194/bac6dd64-9b40-4c98-8d37-10b3bc5d8f80">

**Comment by apoorv1316** [comment]
@rayy40 Are you working on this issue?

**Comment by rayy40** [comment]
> @rayy40 Are you working on this issue?

I am caught up in some work, so I am unable to work on this. You can assign it to someone else. ;(

**Comment by sainikhil1605** [comment]
Hi @apoorv1316  I would like to work on this

**Comment by apoorv1316** [comment]
@sainikhil1605 I've assigned you another issue #1565. Please work on it. You can pick this later
