### ISSUE TITLE
Adding a back to top button

### ISSUE THREAD

**Issue by divyansh14kr** [saeloun/miru-web#1547]
### Describe the solution you'd like

adding a back to top button which pops up only after scrolling

**Comment by Shaba1406** [comment]
I want to work on this issue Please assign this to me

**Comment by akhilgkrishnan** [comment]
@divyansh14kr Could please give more information on this issue. Is this part of Miru website?

**Comment by divyansh14kr** [comment]
Yeah, as a option to improve navigation I think it would be better to add a back to top button since there is a lot of content to scroll through especially on mobile view

**Comment by supriya3105** [comment]
@divyansh14kr Thank you for the suggestion. We will add it to the product website repo. Currently, we are taking contributions on the Miru Application as part of Hacktoberfest. Please check the open list of issues that you might be interested in working.  I can assign it to you.

**Comment by akhilgkrishnan** [comment]
> Yeah, as a option to improve navigation I think it would be better to add a back to top button since there is a lot of content to scroll through especially on mobile view

Seems like its related to Miru marketting website. That is completely a separate private repo. Not directly dependant with Miru app. We'll consider this issue on Miru website.

I'm closing this issue, as it is not part of Miru web application.

Thanks @divyansh14kr for raising.
