### ISSUE TITLE
User Name not displayed on Side Nav Bar in settings 

### ISSUE THREAD

**Issue by sainikhil1605** [saeloun/miru-web#1565]
### Description
When user refreshes any of the page except personal details the name under profile picture is not getting populated
### Environment
    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?
When user refreshes the page user name under profile picture should be populated

### What is the current behaviour?
User name is not populated when page is refreshed

### How to reproduce the issue?

1. Login in to any user in Miru
2.Click on settings on the left navigation bar
3.Go to any tab except Personal Details
4. Refresh the page 
### Screenshots or Screencast

https://github.com/saeloun/miru-web/assets/35322884/c1c830e0-1dc1-4cfa-831c-2c8dd5a3800f

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by sainikhil1605** [comment]
I willing to work on this if the bug is approved

**Comment by apoorv1316** [comment]
@sainikhil1605 Assigned it to you
