### ISSUE TITLE
Can't add client - not sure what field is missing

### ISSUE THREAD

**Issue by anujdeshpande** [saeloun/miru-web#1595]
### Description
Unable to add a client to my Miru account

### Environment

Windows, Chrome (Brave)

### What is the expected behaviour?

Know which fields are mandatory or are malformed.

### What is the current behaviour?

Unable to add client, and can't figure out why.

### How to reproduce the issue?

1. Add contents as above
2. City dropdown is blank
3. Add zipcode, and press Save Changes. Save Changes is greyed out.

### Screenshots or Screencast

![image](https://github.com/saeloun/miru-web/assets/969376/653b39a2-deca-4ec6-a498-14f363cf65c0)
![image](https://github.com/saeloun/miru-web/assets/969376/d2b0363e-d766-4d1b-82c9-8426c0ad901a)

### If the bug is confirmed, would you be willing to submit a PR?

Sure

**Comment by apoorv1316** [comment]
Hi @anujdeshpande, It seems to be an issue with the package we are using. It is not loading the list of cities for the United Kingdom country if you select any state except "England".  The temporary solution would be to select "England" as state and then you can get the list of cities and create a client. We will look into this and fix it soon. Thanks for opening the issue.

**Comment by supriya3105** [comment]
@apoorv1316 Can you open an issue for it in Notion and add the details ?

**Comment by anujdeshpande** [comment]
@supriya3105 I don't think this is fixed - is this only for self-installed instances?

**Comment by supriya3105** [comment]
> @supriya3105 I don't think this is fixed - is this only for self-installed instances?

@apoorv1316 Can you respond to Anuj's query ?  
Also, if the issue is with the package , let's look at another package without this issue.

**Comment by apoorv1316** [comment]
We have removed the dropdowns for state and city. It is now text fields. It will be released tomorrow

**Comment by apoorv1316** [comment]
@anujdeshpande The issue is fixed now. Please refer to the loom video https://www.loom.com/share/2e4b5e5af67845539e5873e84414fd46
