### ISSUE TITLE
Make logo image non-mandatory while setting up organization during user sign up journey 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#1665]

**Comment by nisusam** [comment]
I tried using a couple of approaches with @Dikshadwani :
- Normal Sign-up
- Sign Up with Google

In both these cases, the logo image is non-mandatory. 

Is there any specific edge case, I need to check to reproduce this issue?

cc: @supriya3105, @sonamvg

**Comment by sonamvg** [comment]
It is non-mandatory in cases I have tested on production. Any specific scenario/user or steps to reproduce @supriya3105 ?

**Comment by supriya3105** [comment]
Closing this based on the above confirmation that it is non-mandatory at the moment.
