### ISSUE TITLE
Update PTO entries for January 2024 to reflect in leave tables

### ISSUE THREAD

**Issue by sonamvg** [saeloun/miru-web#1712]
### Description
Currently, PTO's from January 2024 are not reflected in the leave management table. 

### What is the expected behaviour?
All leaves from 1st January 2024 should be reflected in https://app.miru.so/leave-management

### What is the current behaviour?

leaves from February 2024 are shown in leave management

**Comment by prasanthchaduvula** [comment]
Completed https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=b4528f26f4424af7beaf036262796cb3&p=1d0d4b33c3f7402085bfd3f8cba8ecb0&pm=s
