### ISSUE TITLE
Time entry reports page Bugs

### ISSUE THREAD

**Issue by sonamvg** [saeloun/miru-web#1716]
1. Logo for the client is missing in the header but is available in the list view.

![Image](https://github.com/saeloun/miru-web/assets/51998541/a1cfb5c3-c6d8-4c1f-a09b-231b6334e98a)

2. Time entry total changes on every page. The total number of hours should remain consistent for a filter. 

![Image](https://github.com/saeloun/miru-web/assets/51998541/6fb36541-edae-4fbb-a000-518234952069)
![Image](https://github.com/saeloun/miru-web/assets/51998541/6284a7c4-1ffe-4a83-808b-ec30cfe9c8d7)

3.

**Comment by Shruti-Apte** [comment]
As discussed with apoorv and nishant, second bug needs backend changes.
The total duration needs to be calculated at backend for every filter
@apoorv1316 is going to work on it.

**Comment by Shruti-Apte** [comment]
Closing this issue as Logo not reflecting bug is fixed,
and different issue is created for total duration which is assigned to nishant https://github.com/saeloun/miru-web/issues/1746.
