### ISSUE TITLE
Check Sidekiq for multiple emails being sent/retireved

### ISSUE THREAD

**Issue by sonamvg** [saeloun/miru-web#1748]
Recently, on MIRU STAGING, an error occurred and the number of hits on Redis was exhausted.
On debugging, it looked like it was due to multiple email errors.

Need to check if we are trying to resend emails after failure multiple times.

Error:
2024-03-18T08:19:49.632 app[148eddd6ad53e8] ewr [info] [48b00e70-19b2-48bc-a831-a7efc962adaa] RedisClient::CommandError (ERR max daily request limit exceeded. Limit: 10000, Usage: 10000. See https://upstash.com/docs/redis/troubleshooting/max_daily_request_limit for details):

**Comment by gowsik-ragunath** [comment]
Fly free redis DB is limited to a free allowance of 10,000 commands per day. [Ref.](https://fly.io/docs/reference/redis/#pricing)

This is the current Staging redis DB daily usage chart, [Ref.](https://console.upstash.com/flyio/redis)

<img width="1089" alt="Screenshot 2024-03-22 at 10 41 51 AM" src="https://github.com/saeloun/miru-web/assets/52308930/62ab4eb1-1dd8-4e7c-8a8f-356afc02c3ab">

We are getting capped when over 20,000 commands are executed(not sure if there is any individual limit for each [redis commands](https://redis.io/commands/)).

Possible fix:

I found [this discussion](https://community.fly.io/t/managing-redis-rate-limits-on-sidekiq-and-rails/6741/10) where they recommend decreasing the Sidekiq [concurrency](https://community.fly.io/t/managing-redis-rate-limits-on-sidekiq-and-rails/6741/2), and increasing the [fetch timeout](https://community.fly.io/t/managing-redis-rate-limits-on-sidekiq-and-rails/6741/10).

1) We already have concurrency as 1 for both development and production, but please check if this code is actually working,

https://github.com/saeloun/miru-web/blob/81c0337fd73a392c2216e806b326dc9dfd30f691/config/sidekiq.yml#L1-L4

2) Increase the timeout limit for the Sidekiq fetch operation,

Please add the following code snippet to the [sidekiq.rb initializer](https://github.com/saeloun/miru-web/blob/develop/config/initializers/sidekiq.rb) and ensure it's assigned only for the staging app.

https://community.fly.io/t/managing-redis-rate-limits-on-sidekiq-and-rails/6741/10

```
# frozen_string_literal: true

Sidekiq.configure_client do |config|
  config.redis = {
    url: ENV["REDIS_URL"], network_timeout: 5,
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
  }
end

Sidekiq.configure_server do |config|
  config.redis = {
    url: ENV["REDIS_URL"], network_timeout: 5,
    ssl_params: { verify_mode: OpenSSL::SSL::VERIFY_NONE }
  }
  Sidekiq::BasicFetch::TIMEOUT = 15
end
```
