### ISSUE TITLE
Display a user friendly validation message for rate 

### ISSUE THREAD

**Issue by apoorv1316** [saeloun/miru-web#1769]
Display a user-friendly validation message for the rate input field indicating the correct format instead of showing the "NAN" on amount
<img width="1368" alt="Screenshot 2024-03-27 at 6 11 27 PM" src="https://github.com/saeloun/miru-web/assets/18750194/770f5a06-ed7e-4717-975b-5021ff16b221">

**Comment by sonamvg** [comment]
Restrict this field to numerical input.
