### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by Set27** [saeloun/miru-web#1806]
### Description
![image](https://github.com/saeloun/miru-web/assets/49077110/1b400629-4228-47d2-b023-ce4899b19397)

### Environment
Docker + any browser. Nothing in console. Develop branch (main is fine)

**Comment by apoorv1316** [comment]
Hi @Set27. It seems to be working for me in develop branch. Can you please share the logs from the app container. Please use this for reference https://docs.miru.so/contributing-guide/setup/docker
