### ISSUE TITLE
nginx proxy manager  - not sure that it is a bug 

### ISSUE THREAD

**Issue by maksimvelbaum** [saeloun/miru-web#1850]
Hello everyone , 

I'm new here , not sure that it is a bug , but maybe somebody can help me to solve it. 

I using docker to host miru  and  nginx proxy manager to attach domain name , problem that usual host not working for miru ,   instead of  start page i get {"status":"OK","version":{"major":2,"minor":11,"revision":2}}   ,   by direct ip   I get correct page .

Any advice  how possible to solve this page. 

We are in testing mode , maybe exact location will provide more logs 

http://time.boomerangreport.eu/
http://77.37.49.194:3000/

![image](https://github.com/saeloun/miru-web/assets/42903386/ce16358f-b35e-462f-8c55-c7dc792125e1)

**Comment by maksimvelbaum** [comment]
Hi everyone, 
I did another test with Cloudflare on local installation ( ubuntu 24)  and get some blocking 

Blocked hosts: time.boomerangreport.eu
To allow requests to these hosts, make sure they are valid hostnames (containing only numbers, letters, dashes and dots), then add the following to your environment configuration:
    config.hosts << "time.boomerangreport.eu

For more information provided link https://guides.rubyonrails.org/configuring.html#actiondispatch-hostauthorization   but rubyonrails for  is me dark side, I'm only started learning programming on python. 

I added  to  .env   as config.hosts << "time.boomerangreport.eu   and etc/hosts   127.0.0.1       time.boomerangreport.eu   but it didn't help , server of course was restarted after changes, any advices where I need to add config.hosts << "time.boomerangreport.eu ?

**Comment by maksimvelbaum** [comment]
for newbies like me , solution in this file . Case cab be closed all working 


![image](https://github.com/saeloun/miru-web/assets/42903386/9975a17b-4caa-412f-940a-68b0c3e7dd00)

**Comment by nisusam** [comment]
Closing this issue based on the author's recent comment https://github.com/saeloun/miru-web/issues/1850#issuecomment-2175388381. @maksimvelbaum Thank you for your contribution and feedback.
