### ISSUE TITLE
Rescheduling appointments

### ISSUE THREAD

**Issue by rubys** [saeloun/miru-web#666]
Preface: I'm trying to determine whether this package is something that is close enough to my needs to investigate further.  I discovered this package from the following thread on fly.io's community: https://community.fly.io/t/how-can-i-add-the-pupeeteer-buildpack-in-fly-io-which-is-something-similar-to-heroku/7303

I see instructions on how to run the tool, but I don't see documentation on using the tool itself.  If I missed it, my apologies - pointers welcome.

In a nutshell, a dance studio has, say, 6 instructors and 150 students.  Each student purchases a number of lessons, and a lesson lasts 45 minutes.

The requirement is pretty straightforward: I need a view that shows a day in the near future (say, next Tuesday).  A call comes from a student saying they need to move their lesson three hours later.  The instructor that that student usually is paired with is not available - but another is.  Being able to easily (drag/drop) the reservation to a new time would be important.

All I am looking for at this time is an indication of whether this is already supported, a planned feature, patches welcome, or not a good match for this tool.

**Comment by vipulnsward** [comment]
@rubys closing this, I assume the base issue is resolved, please let me know if not :-)

Thanks for your help!
