### ISSUE TITLE
Create a contribution document

### ISSUE THREAD

**Issue by akhilgkrishnan** [saeloun/miru-web#675]
### Is your proposal related to a problem?

Create a new file named CONTRIBUTING.md inside the repo and add all the contributing guidelines and steps to it.

**Comment by aswinikalyan30** [comment]
Can i take this up?

**Comment by akhilgkrishnan** [comment]
> Can i take this up?

@aswinikalyan30 Feel free to take. Let me know if you're any questions.

**Comment by supriya3105** [comment]
@aswinikalyan30 Can you hold on working on this until we add the guidelines that needs to be added to the file.

**Comment by aswinikalyan30** [comment]
sure. let me know when i can start off

**Comment by akhilgkrishnan** [comment]
@aswinikalyan30 There was some conflict with the issue. Because it contains some contribution guidelines as well. We are working on improving the documentation. So If you're interested in helping us on improving the documentation you can check this https://github.com/saeloun/miru-docs repo for that. 
Feel free to join our [Discord](https://discord.gg/w9xKGsVU6H) for more questions and support.
