### ISSUE TITLE
On clicking Miru logo on the left navigation bar, the time tracking page should be loaded. 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#684]
### Is your proposal related to a problem?

There is no way to go to the homepage from other pages. 

### Describe the solution you'd like

On clicking Miru logo on the left navigation bar, the time tracking page should be loaded.

**Comment by ahmedsilat44** [comment]
Hey @supriya3105 its my first time participating in hacktoberfest and I would like to take on this task. If it isn't assigned to anyone could you assign it to me. Thanks 😄

**Comment by Anuran12** [comment]
hi @supriya3105 can you assign it to me ?

**Comment by akhilgkrishnan** [comment]
@Anuran12 Let me know if you need any help on this. Thanks for taking this up 👍

**Comment by aaj013** [comment]
@Anuran12 Let me know if you've dropped this. I'd like to give it a try.

**Comment by Anuran12** [comment]
> @Anuran12 Let me know if you've dropped this. I'd like to give it a try.

okay you can go for it... I am unassigning because I am unable to do that.. Sorry : (

**Comment by aaj013** [comment]
I'd like to give it a try. Assign me if possible. :)

**Comment by supriya3105** [comment]
@aaj013 Assigned you this issue.
