### ISSUE TITLE
The dates are not displayed correctly on day & week view of time tracking page 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#685]
### Description

The dates are not displayed correctly on day & week view of time tracking page 

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

The dates should be displayed as 3rd Oct . Without the 0 for dates between 1-10 of each month. 

### What is the current behaviour?

The dates are displayed as 03rd Oct. 

### How to reproduce the issue?

1. Login in to Miru with you credentials. 
2. Go to time tracking page's day and week view 

### Screenshots or Screencast

<img width="1440" alt="Screenshot 2022-09-29 at 1 21 30 PM" src="https://user-images.githubusercontent.com/91338424/192973138-a38f86f5-a413-4c36-9604-fe722322f1b9.png">

**Comment by Gismo1337** [comment]
please assign me this issue. I would do this.

**Comment by akhilgkrishnan** [comment]
@Gismo1337 Assigned the ticket to you. Let me know if you need any help :). Thanks for taking this up

**Comment by Gismo1337** [comment]
@akhilgkrishnan unassign me to this task. to setup the enviroment as a windows user drives me crazy. not enaugh lifetime left for this.

**Comment by akhilgkrishnan** [comment]
> @akhilgkrishnan unassign me to this task. to setup the enviroment as a windows user drives me crazy. not enaugh lifetime left for this.

@Gismo1337 Yeah I understand. But handling a rails app on windows is kind of crazy🤠. Also I know we are lacking on the documentation. We will work on improving those ASAP.

**Comment by aaj013** [comment]
I'd like to work on this

**Comment by akhilgkrishnan** [comment]
@aaj013 Assigned the ticket to you. Let us know if you need any help on this

**Comment by aaj013** [comment]
> @aaj013 Assigned the ticket to you. Let us know if you need any help on this

Hope this is what expected.
![](https://user-images.githubusercontent.com/5847582/193415615-43886167-a178-4773-b821-4c724027e85d.png)
