### ISSUE TITLE
Update tsconfig.json & alias.js with StyledComponents path.

### ISSUE THREAD

**Issue by prasanthchaduvula** [saeloun/miru-web#686]
### Is your proposal related to a problem?

- Currently to import `styledComponents` in other components we are using relative path imports which is annoying for common reusable styled components.
for example we are doing `import { Badge } from "../../../styledComponents"` in the other components by passing relative path to the styledComponents folder.

### Describe the solution you'd like
`import { Badge } from "StyledComponents"`

Please change the `styledComponents` folder name to `StyledComponents` . Update `tsconfig.js` paths with StyledComponents 
similar to:
```
"paths": {
      // previous code
      "StyledComponents": ["./app/javascript/src/StyledComponents"],
    }
    
```
  Update `alias.js` with `StyledComponents` path similar to 
  ```
module.exports = {
  resolve: {
    alias: {
      // previous code
      StyledComponents: "src/StyledComponents",
    }
  }
};

```

Update the StyledComponents import path across the app like `import { Badge } from "StyledComponents"` instead of relative path.

**Comment by ankitdas09** [comment]
please assign me this issue, I would like to do this.

**Comment by ankitdas09** [comment]
Please assign me this issue.

**Comment by akhilgkrishnan** [comment]
@ankitdas09 Assigned this task to you. Let me know if you need any help on this.

**Comment by ankitdas09** [comment]
`ERROR: ** [Honeybadger] Unable to send error report: API key is missing. id=d67a350e-d109-47b7-98b3-cf0730149c70 level=3 pid=67425`
Getting this error when starting the app with `foreman start -f Procfile.dev`

**Comment by akhilgkrishnan** [comment]
@ankitdas09 It's fine. The issue was because of honeybadger connection.

**Comment by aaj013** [comment]
@ankitdas09 Let me know if you've dropped this. I'd like to give a try.

**Comment by ankitdas09** [comment]
@aaj013 yeah go ahead

**Comment by aaj013** [comment]
Made the mistake of sending PR without assignment. Assign me if above PR can be considered.
