### ISSUE TITLE
On scrolling the website, the header should not get scrolled as well

### ISSUE THREAD

**Issue by amreekminocha** [saeloun/miru-web#687]
Hii.. When you scroll at the website the header gets scrolled as well
It might be better if the header's position gets fixed so that the user can easily tap the logo and come back to the top

**Comment by amreekminocha** [comment]
I can solve this issue as well
I hope it gets listed in the hacktober fest

**Comment by supriya3105** [comment]
@amreekminocha Can you share a video for this issue ?

**Comment by amreekminocha** [comment]
<img width="1440" alt="Screenshot 2022-10-09 at 2 22 25 PM" src="https://user-images.githubusercontent.com/43804941/194747410-c27c9759-360b-44f8-bdc7-2fb2676f5ea6.png">
<img width="1440" alt="Screenshot 2022-10-09 at 2 22 32 PM" src="https://user-images.githubusercontent.com/43804941/194747416-f7e5ba83-80eb-4f98-8868-9b8bf7205bb2.png">

When we scroll, the header goes away... It would be bettter if the header is always visible

**Comment by supriya3105** [comment]
@amreekminocha We are developing a new product website after which this issue will be resolved. Thanks for highlighting this . Appreciate it .
