### ISSUE TITLE
Timesheet entry description field is not scrollable or expandable for edit

### ISSUE THREAD

**Issue by akhilgkrishnan** [saeloun/miru-web#689]
### Description

When creating, If we add a longer description to the timesheet entry, we couldn't be able to scroll through the timesheet entry description while editing.

### Environment

    Linux / MacOS / Android / IOS / Windows
    Mozilla / Chrome / Safari

### What is the expected behaviour?

When we try to edit the timesheet entry, the description field should be scrollable.

### What is the current behaviour?

we couldn't be able to scroll through the timesheet entry description while editing.

### How to reproduce the issue?

1. Go to the time tracking page
2. Create a new timesheet entry with a longer description (use 150 words min)
3. Edit the timesheet entry.
4. Try to scroll the description.

### Screenshots or Screencast

https://www.loom.com/share/611221e8860742feaf0008eebc6f758c

**Comment by sri-rishi** [comment]
Hi @akhilgkrishnan an you assign this to ?

**Comment by akhilgkrishnan** [comment]
@sri-rishi Assigned the ticket to you. Let me know if you need need any help on this.

**Comment by sri-rishi** [comment]
Hi @akhilgkrishnan unassign me this task. setting up the enviroment as a windows user is feel like never ending process.

**Comment by aaj013** [comment]
I'd like to give it a try

**Comment by aaj013** [comment]
Made the mistake of sending PR without assignment. Assign me if above PR can be considered.

**Comment by akhilgkrishnan** [comment]
@aaj013 Your PR looks good. Do not pick more than one issue at the same time. If you have any queries Join our [Discord](https://discord.gg/UABXyQQ82c)

**Comment by aaj013** [comment]
> @aaj013 Your PR looks good. Do not pick more than one issue at the same time.
I have no issues assigned now left to be merged.

**Comment by akhilgkrishnan** [comment]
Reopening this ticket as #695 caused an issue with creating the timesheet entry. So the changes are reverted #705
