### ISSUE TITLE
Dockerize the miru application.

### ISSUE THREAD

**Issue by akhilgkrishnan** [saeloun/miru-web#696]
### Is your proposal related to a problem?

Setting up the Miru app is kind of a crazy process, coz it has a lot of package dependencies and a couple of developers faced issues with setup the app in their environment (Specifically non-Unix, eg: Windows). So It's better to do a dockerize the application, then it is easy to set up in any environment.

### Describe the solution you'd like

Create a docker-composer file and add all the dependencies to it.

**Comment by rajat-tomar** [comment]
Hey, I would like to work on this, can you please assign this to me?

**Comment by rajat-tomar** [comment]
I clicked on the link by mistake, can you please reassign this to me? I'm really sorry for the inconvenience.

**Comment by supriya3105** [comment]
@rajat-tomar Reassigned you this issue.

**Comment by rajat-tomar** [comment]
@akhilgkrishnan @supriya3105 Just wanted to clarify what use case we are trying to solve with this Dockerfile.

Do we need it for local dev builds and runs or would it also be published and used in production deployments?

**Comment by akhilgkrishnan** [comment]
@rajat-tomar It is for the local development

**Comment by rajat-tomar** [comment]
Hey @akhilgkrishnan @supriya3105, I've dockerized the application for local development and raised a PR for the same. Please check PR #720

**Comment by rajat-tomar** [comment]
@akhilgkrishnan update the suggested changes can you please take a look at PR #720
