### ISSUE TITLE
Reduce the size of current password input field on personal settings page

### ISSUE THREAD

**Issue by apoorv1316** [saeloun/miru-web#702]
### Description
Reduce the size of the current password input field and make it equal to the size of the password input
### What is the expected behavior?

All the password input fields should be equal in size.

### What is the current behavior?

The current password input field is larger than the other input fields.

### How to reproduce the issue?

1. Go to settings
2. Click on the personal profile tab 
3. Click on change password

### Screenshots or Screencast
<img width="1780" alt="Screenshot 2022-10-05 at 7 51 09 PM" src="https://user-images.githubusercontent.com/18750194/194084201-7b106d4f-329a-4323-9db8-676e29e75072.png">

**Comment by muditchoudhary** [comment]
Hey, I would like to work on this. But I think if we reduce the size of currentPassword to Password field there will be some black space left on the right of the currentPassword. So is it fine?

**Comment by apoorv1316** [comment]
@muditchoudhary It's fine. See the below image for reference. I am assigning it to you.
<img width="972" alt="Screenshot 2022-10-05 at 8 14 03 PM" src="https://user-images.githubusercontent.com/18750194/194089623-dad86d49-a572-43f7-ad3f-a35961a6b646.png">

**Comment by muditchoudhary** [comment]
okay I'll do it

**Comment by akhilgkrishnan** [comment]
Hi @muditchoudhary   :wave:
Thanks for showing interest in contributing to Miru Web. We've assigned the issue to you.
If you have any questions related to setting up Miru, or any other doubts, feel free to join our Discord community here: [Discord](https://discord.gg/UABXyQQ82c)

**Comment by muditchoudhary** [comment]
Hey, @apoorv1316 and @akhilgkrishnan I could not work on this issue, because I may take a lot of time setting it up locally, which I could not give due to college & other urgencies. I want you to unassign me and assign this issue to someone else.

Thank you!!

**Comment by akhilgkrishnan** [comment]
@muditchoudhary No worries. Which environment were you tried? Is that windows?

**Comment by muditchoudhary** [comment]
> @muditchoudhary No worries. Which environment were you tried? Is that windows?

Nope Ubuntu

**Comment by akhilgkrishnan** [comment]
Did you followed this https://saeloun.github.io/miru-docs/docs/contributing-guide/setup/ubuntu-debian documentation

**Comment by muditchoudhary** [comment]
No, I didn't. I assumed that It will be going to take a lot of time.

**Comment by rajat-tomar** [comment]
Hey @akhilgkrishnan , can you please assign this task to me if no one is working on it?

**Comment by akhilgkrishnan** [comment]
@rajat-tomar Assigned the ticket to you.

**Comment by rajat-tomar** [comment]
@akhilgkrishnan I've solved the issue and raised a PR for the same. Please check PR #728

**Comment by apoorv1316** [comment]
Thanks, @rajat-tomar for working on it.
