### ISSUE TITLE
Client name and project name should be in capitalized case

### ISSUE THREAD

**Issue by apoorv1316** [saeloun/miru-web#703]
### Description
The client name and project name should be capitalized case. If I create a client with the name "sony entertainment" it should be shown as "Sony Entertainment" on the client list page ("/clients"). The project name should also be capitalized.

### What is the expected behavior?

Capitalize client name and project name
<img width="1781" alt="Screenshot 2022-10-05 at 8 25 26 PM" src="https://user-images.githubusercontent.com/18750194/194092956-4323aabe-f554-4ce4-bac8-3a04d80cb5f5.png">
<img width="1774" alt="Screenshot 2022-10-05 at 8 28 04 PM" src="https://user-images.githubusercontent.com/18750194/194093427-8f161bac-f11a-4702-8ff0-af45eb78d79f.png">

### How to reproduce the issue?

1. Go to clients or projects
2. Create a new client or project with the name in lowercase

**Comment by sotiriszogos** [comment]
Hello, I could fix that. Could you please assign it to me?

**Comment by apoorv1316** [comment]
@sotiriszogos Assigned it to you

**Comment by amreekminocha** [comment]
Hi is this issue solved?
If not, you can assign it to me

**Comment by sotiriszogos** [comment]
Hello, @akhilgkrishnan and @amreekminocha. Because I'm having difficulties during the installation of the required packages, you can assign it to @amreekminocha in order to fix it sooner. It is fine from my side

**Comment by akhilgkrishnan** [comment]
@amreekminocha Assigned the ticket to you.

**Comment by rajat-tomar** [comment]
@akhilgkrishnan , is @amreekminocha working on this? If not, I would like to work on this!
Thanks!

**Comment by amreekminocha** [comment]
@akhilgkrishnan 
I just got assigned with the work...
I will start working on it very soon

**Comment by apoorv1316** [comment]
Hey, @amreekminocha Any update on this ticket? Do let me know if you need help with this.

**Comment by rajat-tomar** [comment]
Hi Apoorv,
It's just that I'm stuck with the office work and I'm taking it along. I'll
try to finish this on the weekend. For sure I'll reach out for help
wherever needed.
Thanks!

**Comment by KenRoda** [comment]
Hello, I have resolved this issue. I'm going to create a pull request. Can you please assign this to me?

**Comment by KenRoda** [comment]
I have a question. For example, "Flipkart.com" looks  like "Flipkart.Com” when I apply `text-transform: capitalize;` to resolve the issue.  Is there any problem with this?

**Comment by KenRoda** [comment]
Hi @apoorv1316  @akhilgkrishnan , I have created a PR for this issue. Please check PR https://github.com/saeloun/miru-web/pull/954
