### ISSUE TITLE
Update time-tracking folder to TimeTracking in src/components

### ISSUE THREAD

**Issue by prasanthchaduvula** [saeloun/miru-web#706]
**Bug:** 
currently `time-tracking` folder inside `app/javascript/src/components/` is not following our naming convention.

**Solution**
Rename the `time-tracking` folder to `TimeTracking` inside `app/javascript/src/components/` & update component import paths respectively.

**Comment by camperjett** [comment]
I can do it :)

**Comment by isurumaldeniya** [comment]
@prasanthchaduvula Hi I would like to work on this. Can you assigned me this

**Comment by manav-06** [comment]
Hi, @prasanthchaduvula I would like to work on this

**Comment by prasanthchaduvula** [comment]
@akhilgkrishnan Please assign this issue to someone from above.

**Comment by akhilgkrishnan** [comment]
Hi @camperjett   :wave:
Thanks for showing interest in contributing to Miru Web. We've assigned the issue to you.
If you have any questions related to setting up Miru, or any other doubts, feel free to join our Discord community here: [Discord](https://discord.gg/UABXyQQ82c)

**Comment by akhilgkrishnan** [comment]
@isurumaldeniya @manav-06 We assign the issues based on FCFS. Please keep watch on the issues for more issues.

**Comment by isurumaldeniya** [comment]
@akhilgkrishnan Sure. Thank you for the reply. Hope to contribute to the project in the future 😊

**Comment by akhilgkrishnan** [comment]
@isurumaldeniya  Feel free to join our Discord community here: [Discord](https://discord.gg/UABXyQQ82c) for more updates.
