### ISSUE TITLE
Use Badge components across the app

### ISSUE THREAD

**Issue by prasanthchaduvula** [saeloun/miru-web#708]
### Present:
Recently we created `Badge` reusable StyledComponent. Instead of custom code & styling we have to reuse it across the frontend. Wherever we have these below styling like projects, invoices, clients in all component view we have below Badges. In all these components we written custom styling. Lets use the `Badge ` component in the code base. Wherever there is `getStatusCssClass` mostly the styling is related to `Badge` type style. 

<img width="176" alt="Screenshot 2022-10-06 at 10 08 27 AM" src="https://user-images.githubusercontent.com/52771571/194215344-3592e926-717c-4cf7-a027-512c5f8d5445.png">

### Solution

**Default style**
<img width="87" alt="Screenshot 2022-10-06 at 10 16 55 AM" src="https://user-images.githubusercontent.com/52771571/194216469-2112ac36-863d-4921-b38a-f31962034ac6.png">
```
import { Badge } from "StyledComponents"

<Badge />
```

**Updating Props to customise the style**
<img width="103" alt="Screenshot 2022-10-06 at 10 20 36 AM" src="https://user-images.githubusercontent.com/52771571/194216947-940363d0-c3e8-4078-922d-41f5992eb56e.png">

Where ever we need `Badge` component. use `className` to override the default styles. For color codes,  please check `tailwind.config.js` file. 

```
import { Badge } from "StyledComponents"

<Badge
     text="non billable"
     color="text-miru-dark-purple-600"
      bgColor="bg-miru-dark-purple-100"
      className="uppercase"
  />
```

**Comment by isurumaldeniya** [comment]
@prasanthchaduvula Hi I would like to work on this. Can you please guide me?

**Comment by prasanthchaduvula** [comment]
Hi @isurumaldeniya   :wave:
Thanks for showing interest in contributing to Miru Web. We've assigned the issue to you.
If you have any questions related to setting up Miru, or any other doubts, feel free to join our Discord community here: [Discord](https://discord.gg/UABXyQQ82c)

**Comment by prasanthchaduvula** [comment]
@manav-06 We assign the issues based on FCFS. Please keep watch on the issues for more issues.

**Comment by manav-06** [comment]
@supriya3105 you can assign this to me if needed

**Comment by mayankagnihotri7** [comment]
@supriya3105 @prasanthchaduvula @akhilgkrishnan  Can I take this up if the assigned person is not working?

**Comment by prasanthchaduvula** [comment]
@isurumaldeniya We assigned this issue to @mayankagnihotri7 as we noticed a delay
