### ISSUE TITLE
Removed duplicate default scope from client model

### ISSUE THREAD

**Issue by akhilgkrishnan** [saeloun/miru-web#710]
### Description

In the client model, we are having 2 default_scopes that perform the same actions. https://github.com/saeloun/miru-web/blob/6a4877d222260b2442709733686340d92766476c/app/models/client.rb#L34 and https://github.com/saeloun/miru-web/blob/6a4877d222260b2442709733686340d92766476c/app/models/client.rb#L45.

`kept` is a default method for getting all the undiscarded record (which mean discarded_at: nil). So we can remove `default_scope { where(discarded_at: nil) }` from client.rb model.

**Comment by SabujGolui** [comment]
assign it to me pls. I'll be more than pleased to assist.

**Comment by akhilgkrishnan** [comment]
Hi @SabujGolui   :wave:
Thanks for showing interest in contributing to Miru Web. We've assigned the issue to you.
If you have any questions related to setting up Miru, or any other doubts, feel free to join our Discord community here: [Discord](https://discord.gg/UABXyQQ82c)

**Comment by SabujGolui** [comment]
updated client,rb file pls check it PR #714
