### ISSUE TITLE
Users should not be able to edit and delete a billed time tracking entry. 

### ISSUE THREAD

**Issue by supriya3105** [saeloun/miru-web#711]
### Is your proposal related to a problem?

  Currently, employees are able to edit and delete their time entries which are billed which causes confusion in invoicing. 

### Describe the solution you'd like

 Once the time tracking entry of an employee is billed i.e. added to an invoice and sent to client, the employee should not be able to edit or delete that time entry . We need to remove the edit and delete icon for billed time tracking entries. 

The admin and owner role should still be able to edit and delete those entries.

**Comment by mayankagnihotri7** [comment]
@akhilgkrishnan @supriya3105 Can I please work on this issue?
