### ISSUE TITLE
Bug in the line items list when editing a line item

### ISSUE THREAD

**Issue by apoorv1316** [saeloun/miru-web#722]
### Description
While editing a line item we are getting the date of it(already added line item) in the new line items list. 

### What is the expected behavior?

The date of entry which is in edit mode should not be visible on the new items list

### What is the current behavior?

While editing a line item we are getting the date of it(already added line item) in the new line items list. 

### How to reproduce the issue?

1. Go to invoices and click on new Invoice
2. Select a Client (E.g. Flipkart or Microsoft)
3. Click on the new line item button and  add an entry
4. On the added entry click on the three dots menu icon and click Edit entry
5. Now click on the new line item button again and we can see the date of entry(of step 4) is visible in the list

### Screenshots or Screencast
Loom: https://www.loom.com/share/fc94274fdb4c4369a07458405304a2ad

**Comment by rajat-tomar** [comment]
@apoorv1316 Can you please assign this to me. I would like to work on this

**Comment by apoorv1316** [comment]
Sure assigned it to you @rajat-tomar

**Comment by rajat-tomar** [comment]
Hey @apoorv1316 just raised the PR for the issue. Please check PR#737

**Comment by apoorv1316** [comment]
Thanks @rajat-tomar for contributing to miru
