### ISSUE TITLE
Not able to update the date while adding new time entry

### ISSUE THREAD

**Issue by sudeeptarlekar** [saeloun/miru-web#770]
### Description
Change of date is not possible while adding new time entry.

### Environment
Production(app.miru.so)
FireFox(v106.0.3 64-bit)

### What is the expected behaviour?
User should be able to change the date for new time entries.

### What is the current behaviour?
User is not able to change the date for time entry, forcing user to cancel the new time entry and start from new again.

### How to reproduce the issue?

1. Go to time tracking page and click new time entry.
2. Try to change date for new time entry and observe that user is not able to update the date for the time entry.

### Screenshots or Screencast
https://user-images.githubusercontent.com/23317691/200542572-00a26cfd-38da-4d7f-b8ed-dd515188b248.mp4

### Any possible solutions?
Add date dropdown

### If the bug is confirmed, would you be willing to submit a PR?
Yes

**Comment by vipulnsward** [comment]
@apoorv1316 please re-verify

**Comment by apoorv1316** [comment]
Opened a ticket for it https://www.notion.so/saeloun/6afc9500b2cc42af86be55f37894fb09?v=b4528f26f4424af7beaf036262796cb3&p=24cca74fa3a64daeb046e0a34b83eb7c&pm=s

**Comment by supriya3105** [comment]
This has been fixed in the PR https://github.com/saeloun/miru-web/pull/967. Hence closing this issue.
