### ISSUE TITLE
Move CI to buildkite

### ISSUE THREAD

**Issue by vipulnsward** [saeloun/miru-web#787]
@xrimpy what is the status of this?

**Comment by xrimpy** [comment]
Waiting ng on your digital ocean kyc.

I am unable to access servers as the account is locked

**Comment by xrimpy** [comment]
Apart from that the builds I showed you on Wednesday are using build kite only

**Comment by swaathi** [comment]
@xrimpy lmk if you need anything here. Vipul mentioned that we need to move away from Github CI ASAP.

**Comment by supriya3105** [comment]
@xrimpy As I understand this issue is done, can you please close it if its that correct.
