### ISSUE TITLE
Fix slow loading times on Invoices page

### ISSUE THREAD

**Issue by vipulnsward** [saeloun/miru-web#966]
The average load times on Invoices page API is now 3seconds. It will continue to go up with more records.

We need to speed it up

https://www.notion.so/saeloun/Fix-slow-loading-times-on-Invoices-page-382c353f4fd2454d9fa0985bd23cc2a7

https://www.notion.so/saeloun/Update-query-for-recently-updated-invoices-to-reduce-the-query-time-1a79d6bd6e9f48098d75ed096e8f020a

cc @shalapatil  / @supriya3105

**Comment by supriya3105** [comment]
@shalapatil check APM on Kibana . Check controller there. Will give you a breakdown of the performance of each query.

**Comment by supriya3105** [comment]
Assigned to Prasanth as it was due to some recent refactoring work done by Prasanth on recently updated invoices part of the page.
